dependencies:
  - coverage
  - pandas
  - geopandas
  - matplotlib-base
  - pyarrow
  - pykrige
  - pyproj
  - pytest
  - pytest-cov
  - setuptools_scm
  - shapely
  # For docs
  - sphinx
  - streamlit
  - tqdm
