name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    defaults:
      run:
        # Ensure environment gets sourced between steps
        shell: bash -l {0}
    name: Python (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4

          # setup conda-forge with micromamba
    - name: Setup Python
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        condarc: |
          channels:
            - conda-forge
            - defaults
        create-args: >-
          python=${{ matrix.python-version }}
        environment-name: prod
        cache-environment: true

    - name: Install pyritas
      run: |
        set -e
        poetry install

    - name: Run tests
      run: |
        set -e
        python -m pytest --cov=pyritas
        python -m coverage xml

    - name: Upload coverage
      if: ${{ matrix.python-version == '3.11' }}
      uses: codecov/codecov-action@v3
      with:
        token: $${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
